### ISSUE TITLE
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 443

### ISSUE THREAD

**Issue by abhimanuhandoo** [oktadeveloper/okta-legacy-with-cloud-gateway-example#5]
Hi @briandemers,

I am able to successfully run this application on my local however unable to run on my server where I am using the custom configuration of okta instead of default provided by my company.

I am able to get the login form of okta and after that getting "

2020-07-09 00:30:39.035 ERROR 5981 --- [ctor-http-nio-1] a.w.r.e.AbstractErrorWebExceptionHandler : [2beae42a] 500 Server Error for HTTP GET "/login/oauth2/code/okta?code=x7E2mYsXEpJINsuLfLSw&state=QfvZ-kQq247e5J5iWNPpnY0KxGYi5hdBDAYkthCoIww%3D" io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: for port number okta domaninname:443

I did telnet domainname 443 and the result is same connection refused.

Wanted to know why application trying to access 443 port in this case and is there anyway to skip this call.

Thanks,
Abhimanu Handoo

**Comment by abhimanuhandoo** [comment]
Hi,

Can anybody help me with this issue.

Thanks,
Abhimanu Handoo

**Comment by mraible** [comment]
@abhimanuhandoo Are you able to make this work with a brand new developer org? I'm guessing that your company has a different configuration than the default developer org (that this post was written for).

**Comment by akkulreddy** [comment]
@mraible Is this been resolved? I am Facing the same issue. Have taken the code from this link https://github.com/oktadev/okta-spring-security-5-example and its been working fine in local network. Both okta login as well as user info API calls. Where as in client network only login API is working and Userinfo API is failing. So needed some suggestions here

**Comment by mraible** [comment]
Are you behind a proxy? If so, you might need to configure your proxy in your Spring Boot app. https://github.com/okta/okta-spring-boot#proxy

**Comment by akkulreddy** [comment]
@mraible Login with okta is happening in Angular client server. By using that same token which got generated I need to utilize and allow the user to access the microservices which is in spring boot. That's exactly the requirement I am trying to achieve. The Above mentioned Example you have been mentioned explains when login also happens from spring boot itself.

**Comment by mraible** [comment]
Does your issuer end in /oauth2/default or did you create a custom authorization server? Your org authentication server can't validate tokens. Only a custom AS can do that. https://developer.okta.com/docs/concepts/auth-servers/

**Comment by akkulreddy** [comment]
Issue was the proxy details which has been set at vm arguments was not taking  by web client. Had created rest template by rest template factory along with proxy it started working .. thank @mraible for your time
